[[headers]]
  for = "/*"
  [headers.values]
    # Esto le dice al navegador que no bloquee las peticiones a 127.0.0.1
    Content-Security-Policy = "upgrade-insecure-requests"

[[redirects]]
  # Si alguien entra por HTTPS, lo mandamos a HTTP
  from = "https://*"
  to = "http://:splat"
  status = 301
  force = true
